### ISSUE TITLE
TypeError: argument of type 'NoneType' is not iterable

### ISSUE THREAD

**Issue by fascenda** [bpaauwe/RokuPoly#7]
Sorry to bother you again, even more sorry that I tried to update Roku and started down this path.  Now I have UNInstall the RokuPoly, install it again to the latest version, restart the raspberryPi, restart the ISY, and I still have the result that nothing responds.  And I can't get it to show the Nodes (it shows only 1 node where before it showed 3 nodes).

Something I missed?

I have two Roku devices in the custom parameters, they are listed in the attached log 
   RokuTCL32 with ip 10.0.0.31
   RokuPremiere with ip 10.0.0.80

It gets the channels list from the RokuTCL32 then encounters this error, I never see it get discovery of the RokuPremiere.

TypeError: argument of type 'NoneType' is not iterable

I hate to give up on this but... if there is nothing obvious I will let it rest (for awhile anyway).

Thanks in advance.

[RokuPolyLog.txt](https://github.com/bpaauwe/RokuPoly/files/9727849/RokuPolyLog.txt)

**Comment by bpaauwe** [comment]
I think it's the rokuPremier that it gets the channel list for.  It looks like it can't connect to the other one.

roku:discover: Query failed for 10.0.0.31

then
HTTPConnectionPool(host='10.0.0.31', port=8060): Max retries exceeded with url: /query/active-app (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0xb5db34b0>: Failed to establish a new connection: [Errno 113] No route to host'))

The node server isn't handling the fact that it can't connect to one of the configured Roku's and fails

**Comment by fascenda** [comment]
Okay yeah I see the request for 10.0.0.31 was in the midst of the response from 10.0.0.80 and that threw me off.
I don't really care about 10.0.0.31 so I've removed that and now it looks better.

Still have that problem with the 562859 but that's a separate item.

Sorry for that.  Gosh I'm glad I retired from software work this diagnostic stuff isn't fun anymore.  :-)

2022-10-03 16:56:12,157 MQTT       polyinterface      DEBUG    roku:discover: {'ip': '10.0.0.31', 'configured': False, 'node_id': 'roku_31', 'apps': None}
2022-10-03 16:56:12,158 MQTT       polyinterface      INFO     roku:discover: query 10.0.0.31
